# Generated by Django 3.1.2 on 2020-11-01 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SymbolTitle', models.CharField(max_length=30)),
                ('TimeFrame', models.CharField(default='1D', max_length=30)),
                ('NowPrice', models.CharField(max_length=30)),
                ('TriggerPrice', models.CharField(max_length=30)),
                ('StopLoss', models.CharField(max_length=30)),
                ('TakeProfit1', models.CharField(max_length=30)),
                ('TakeProfit2', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TakeProfit3', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('TakeProfit4', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('LivePrice', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsStopped', models.BooleanField(default=True)),
                ('IsTriggered', models.BooleanField(default=True)),
                ('IsTakeProfited1', models.BooleanField(default=True)),
                ('IsTakeProfited2', models.BooleanField(default=True)),
                ('IsTakeProfited3', models.BooleanField(default=True)),
                ('IsTakeProfited4', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('Images', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('TelegramMessageId', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
